11 task
niksaz/spbau-java pull request #6
Opened 2017-02-23 12:17 UTC by niksaz

2017-02-24 07:35 UTC, jzuken requested changes

2017-02-24 07:35 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/SingleThreadedLazy.java
> +    private Holder<T> result;
ну вообще Holder -- это чит, конечно, предполагалось без него. но ладно, одно такое решение я готов принять

2017-02-24 07:35 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/SingleThreadedLazy.java
> + * Implementation of <a href="Lazy.html">Lazy interface</a>
javadoc может генерировать не только html, но и pdf, например. поэтому лучше ссылаться на другие сущности в комментариях только через @link

2017-02-24 07:35 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/SingleThreadedLazy.java
> +            result = new Holder<>(computation.get());
после того, как мы сделали вычисление и сохранили результат, computation нам больше не нужен. имеет смысл его занулить, чтобы сборщик мусора не думал, что он нам ещё нужен

2017-02-24 07:35 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/MultiThreadedLazy.java
> +    public synchronized T get() {
работать будет, но уж больно медленно. ну то есть если значение уже посчитано, синхронизация для всего метода не имеет смысла. давайте попробуем её локализовать

2017-02-24 07:35 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/LockFreeLazy.java
> +    // used to update field if we have different threads performing computations
а чего тут обычный комментарий?

2017-02-24 21:51 UTC, niksaz commented on src/main/java/ru/spbau/sazanovich/nikita/LockFreeLazy.java
> +    // used to update field if we have different threads performing computations
думал, что не следует использовать обширные комментарии, когда описываешь какое-то private поле и его внутреннюю работу. но, наверное, следует его сделать в javadoc стиле.

2017-02-27 18:55 UTC, jzuken commented
зачтено, 10

2017-12-03 20:49 UTC, closed without merging