12 task
niksaz/spbau-java pull request #7
Opened 2017-03-17 20:43 UTC by niksaz

MyGit -- VCS system. 
Similar architecture to original Git. There are Commits, Branches, Trees, Blobs. Commit point to the roots of corresponding Trees. Branches contain links to Commits. Trees represent directories in filesystems, blobs -- files.
All files are identified by their hash code which is provided by SHA-1 algorithm.

2017-03-18 14:21 UTC, jzuken requested changes

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/console/CommandLineArgsHandler.java
> +        if (args.length == 0) {
я думаю, тут было бы уместно применить https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html. это позволило бы обойтись без этих else

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/console/CommandLineArgsHandler.java
> +     * @return {@code true} if parsed successfully; {@code false} otherwise
ну это немного неправда. оно вернёт true, если передана поддерживаемая команда, а это не совсем то же самое. вообще это интересный момент, почему оно именно возвращает bool, а не бросает что-нибудь типа ArgumentNotSupportedException?

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/console/CommandLineArgsHandler.java
> +                    printStream.println(ADD_CMD + " requires some files to have an effect");
а теперь на секунду представим, что следующее задание будет написать GUI-интерфейс к этому коду. придётся строки парсить? ну то есть да, можно будет просто показать его содержимое пользователю, а если захочется какую-то более сложную логику делать, что тогда?

2017-03-18 14:21 UTC, jzuken commented on README.md
там в задании требовалось создать краткое описание внутренней архитектуры, вот его лучше поместить сюда

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGit.java
> +        } else {
а else тут не нужен тогда

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGit.java
> +public class MyGit {
а можно как-то пояснить смысл выделения этого класса персонально под init()? просто получается, что класс с таким громким и важным в данном контексте именем делает только одну команду и с остальными вообще никак не связан

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/Mapper.java
> +class Mapper {
может его как-то иначе обозвать? а то с описанием выше оно как-то не стыкуется

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGitHandler.java
> +    private String rebuildTree(@Nullable Tree tree, @NotNull Path prefixPath, @NotNull Set<Path> indexedPaths)
это очень большой метод, надо разбить его на несколько более простых и понятных

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGitHandler.java
> +    private List<Change> getChangeList(@Nullable Tree tree, @NotNull Path prefixPath, @NotNull Set<Path> indexedPaths)
и этот явно тоже стоит разбить

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGitHandler.java
> +    private TreeEdge updateBlobIfIndexed(@NotNull TreeEdge object, @NotNull Path path,
этот класс какой-то очень умный получается: он знает и про бизнес-логику приложения, и про внутреннее устройство репозитория. такое приложение крайне сложно менять, если, например, захотим начисто переделать всю структуру .mygit. я предлагаю явно выделить несколького слоёв и чётко разбить функциональность между ними, чтобы каждый отвечал только за что-то своё.

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/status/Change.java
> +public class Change {
изменение характеризуется только путём и всё?
может его абстрактным сделать, чтобы более понятно было, что он базовый класс для остальных?

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/status/UntrackedFile.java
> +public class UntrackedFile extends Change {
это наследование с текущими именами классов выглядит очень странно. мне кажется, тут стоит немного переработать сущности (возможно, просто найти более удачные имена)

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/objects/Commit.java
> +public class Commit implements Serializable, Comparable<Commit> {
а если использовать какой-нибудь https://projectlombok.org/features/index.html, этот класс скорее всего в один экран влезет со всеми комментариями

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/logs/CommitLog.java
> +public class CommitLog {
а чем оно принципиально от Commit отличается, ну кроме того, что в другом пакете лежит?

2017-03-18 14:21 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/logs/package-info.java
> + * Contains objects which are returned by the library to the user about log info.
раскидывать код по пакетам в соответствии с пользовательскими командами кажется мне не лучшей идеей. лучше группировать их по назначению, по решаемым задачам, по уровню абстракции. а так получается, что код, связанный с тем же коммитом, например, раскидан по всей системе

2017-03-18 14:53 UTC, niksaz commented on src/main/java/ru/spbau/sazanovich/nikita/console/CommandLineArgsHandler.java
> +     * @return {@code true} if parsed successfully; {@code false} otherwise
это и подразумевалось -- мне кажется, что имеет смысл парсить команду iff она поддерживаема. а насчет Exception-ов, возможно вы правы. но полагалось, что это клиентский код и он написан специально для terminal-а, а в терминале, многого не сделать. для иных пользователей (GUI) предлагается использовать команды напрямую, а не парсить их.

2017-03-18 14:56 UTC, niksaz commented on src/main/java/ru/spbau/sazanovich/nikita/console/CommandLineArgsHandler.java
> +        if (args.length == 0) {
тут же хотелось, чтобы все таки управление дошло до конца и один и тот же код использовать для всех:
        showHelp();
        return false;
но если перейти на исключение, то было бы полезно так сделать. действительно, многовато уровней.

2017-03-18 14:58 UTC, niksaz commented on README.md
да, я поместил это в pull-request. все же лучше действительно перенести его в README.

2017-03-18 15:05 UTC, niksaz commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/logs/CommitLog.java
> +public class CommitLog {
ну хотелось бы, чтобы он просто был контейнером какой-то информации из библиотеки. а внутри уже для Commit наверное можно и public методы будет потом дописывать, которые производят какие-то изменения, знаю о структуре. 
думаете, если Commit будет делать сам изменения, то тогда это плохое разбиение (т.е. для этого подошел бы другой класс, который использует Commit)?
ну и еще там hash-а нет в Commit-е, а в CommitLog-е нет списка детей. и кажется делать общий класс для них типа CommitBase(заключаю туда author, message, dateCreated) нерационально. или я заблуждаюсь.

2017-03-18 18:37 UTC, niksaz commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/MyGit.java
> +public class MyGit {
там просто когда методы из MyGitHandler, то они изначально ищут directory .mygit, и если ее нет, то кидают исключение. метод же в MyGit просто создает ее, ему не нужна директория. хотелось их разделить.
но действительно странно, лучше пусть в Handler-е static будет.

2017-04-16 07:05 UTC, jzuken commented on src/main/java/ru/spbau/sazanovich/nikita/mygit/logs/CommitLog.java
> +public class CommitLog {
да не, я не против разделения информации. просто у них сейчас у обоих есть поля message, author и dateCreated. они чем-то отличаются или просто дублируют друг друга?

2017-12-03 20:49 UTC, closed without merging